version: 2

builds:
  - id: velocity
    main: .
    binary: velocity-{{ .Os }}-{{ .Arch }}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: velocity
    ids:
      - velocity
    name_template: "velocity-{{ .Os }}-{{ .Arch }}"
    formats:
      - tar.gz

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - name: velocity
    repository:
      owner: velocitykode
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/velocitykode/velocity-cli"
    description: "CLI for the Velocity Go web framework"
    license: "MIT"
    install: |
      if Hardware::CPU.arm?
        bin.install "velocity-darwin-arm64" => "velocity"
      else
        bin.install "velocity-darwin-amd64" => "velocity"
      end
    test: |
      assert_match "VELOCITY CLI", shell_output("#{bin}/velocity version")
